### ISSUE TITLE
Instructions how to use react-native-dynamic-bundle-restore

### ISSUE THREAD

**Issue by elmcapp** [killserver/react-native-dynamic-bundle-restore#1]
I am seeking for instruction on how to use this library

1. how do we create a bundle for iOS
2. if the bundle is hosted at a remote server how do we call it

Could you replay here or update the instructions on how to do the following. Thank you in advance

**Comment by killserver** [comment]
Greetings.
1) I use this command:
react-native bundle --platform ios --dev false --entry-file index.js --bundle-output ./main.bundle --assets-dest ./ios
2) bundle need download in device. "remote" bundle not support.
example how download and activate bundle here:
https://github.com/killserver/react-native-dynamic-bundle-restore/blob/main/example/App.js#L49

I usually archive and send the bundle to the server. In the application, I make a request to the endpoint where compare versions and give a link to the desired bundle for current user
